name: 🔒 Chall 4 - Look mom, without env
on:
  issues:
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'chall4' }}
    steps:
      - name: Check my flag is correctly masked
        run: "echo Flag: ${{ secrets.FLAG }}"

      - name: Unsafe right ?
        run: "echo Body: ${{ github.event.issue.body }}"

      - name: But whatever
        run: "echo Void: "
