name: 🔒 Chall 1 - I won't say my password

on:
  issue_comment:
    types: [created, edited]
    
permissions:
  issues: write

jobs:
  chall:
    runs-on: ubuntu-latest
    steps:        
    - name: View issue information
      run: |
        echo '${{ github.event.comment.body }}'
      env:
        FLAG: ${{ secrets.FLAG1 }}
